INSERT ALL
INTO Country (id, Name) VALUES (1, 'Afganistan')
INTO Country (id, Name) VALUES (2, 'Albania')
INTO Country (id, Name) VALUES (3, 'Alemania')
INTO Country (id, Name) VALUES (4, 'Andorra')
INTO Country (id, Name) VALUES (5, 'Angola')
INTO Country (id, Name) VALUES (6, 'Antigua y Barbuda')
INTO Country (id, Name) VALUES (7, 'Arabia Saudita')
INTO Country (id, Name) VALUES (8, 'Argelia')
INTO Country (id, Name) VALUES (9, 'Argentina')
INTO Country (id, Name) VALUES (10, 'Armenia')
INTO Country (id, Name) VALUES (11, 'Australia')
INTO Country (id, Name) VALUES (12, 'Austria')
INTO Country (id, Name) VALUES (13, 'Azerbaiyán')
INTO Country (id, Name) VALUES (14, 'Bahamas')
INTO Country (id, Name) VALUES (15, 'Bangladés')
INTO Country (id, Name) VALUES (16, 'Barbados')
INTO Country (id, Name) VALUES (17, 'Baréin')
INTO Country (id, Name) VALUES (18, 'Bélgica')
INTO Country (id, Name) VALUES (19, 'Belice')
INTO Country (id, Name) VALUES (20, 'Benín')
INTO Country (id, Name) VALUES (21, 'Bielorrusia')
INTO Country (id, Name) VALUES (22, 'Birmania')
INTO Country (id, Name) VALUES (23, 'Bolivia')
INTO Country (id, Name) VALUES (24, 'Bosnia y Herzegovina')
INTO Country (id, Name) VALUES (25, 'Botsuana')
INTO Country (id, Name) VALUES (26, 'Brasil')
INTO Country (id, Name) VALUES (27, 'Bulgaria')
INTO Country (id, Name) VALUES (28, 'Burkina Faso')
INTO Country (id, Name) VALUES (29, 'Burundi')
INTO Country (id, Name) VALUES (30, 'Bután')
INTO Country (id, Name) VALUES (31, 'Cabo Verde')
INTO Country (id, Name) VALUES (32, 'Camboya')
INTO Country (id, Name) VALUES (33, 'Camerún')
INTO Country (id, Name) VALUES (34, 'Canadá')
INTO Country (id, Name) VALUES (35, 'Catar')
INTO Country (id, Name) VALUES (36, 'Chad')
INTO Country (id, Name) VALUES (37, 'Chile')
INTO Country (id, Name) VALUES (38, 'China')
INTO Country (id, Name) VALUES (39, 'Chipre')
INTO Country (id, Name) VALUES (40, 'Ciudad del Vaticano')
INTO Country (id, Name) VALUES (41, 'Colombia')
INTO Country (id, Name) VALUES (42, 'Comoras')
INTO Country (id, Name) VALUES (43, 'Congo')
INTO Country (id, Name) VALUES (44, 'Corea del Norte')
INTO Country (id, Name) VALUES (45, 'Corea del Sur')
INTO Country (id, Name) VALUES (46, 'Costa de Marfil')
INTO Country (id, Name) VALUES (47, 'Costa Rica')
INTO Country (id, Name) VALUES (48, 'Croacia')
INTO Country (id, Name) VALUES (49, 'Cuba')
INTO Country (id, Name) VALUES (50, 'Curazao')
INTO Country (id, Name) VALUES (51, 'Chipre del Norte')
INTO Country (id, Name) VALUES (52, 'Dinamarca')
INTO Country (id, Name) VALUES (53, 'Dominica')
INTO Country (id, Name) VALUES (54, 'Ecuador')
INTO Country (id, Name) VALUES (55, 'Egipto')
INTO Country (id, Name) VALUES (56, 'El Salvador')
INTO Country (id, Name) VALUES (57, 'Emiratos Árabes Unidos')
INTO Country (id, Name) VALUES (58, 'Eritrea')
INTO Country (id, Name) VALUES (59, 'Eslovaquia')
INTO Country (id, Name) VALUES (60, 'Eslovenia')
INTO Country (id, Name) VALUES (61, 'España')
INTO Country (id, Name) VALUES (62, 'Estados Unidos')
INTO Country (id, Name) VALUES (63, 'Estonia')
INTO Country (id, Name) VALUES (64, 'Eswatini')
INTO Country (id, Name) VALUES (65, 'Etiopía')
INTO Country (id, Name) VALUES (66, 'Filipinas')
INTO Country (id, Name) VALUES (67, 'Finlandia')
INTO Country (id, Name) VALUES (68, 'Fiyi')
INTO Country (id, Name) VALUES (69, 'Francia')
INTO Country (id, Name) VALUES (70, 'Gabón')
INTO Country (id, Name) VALUES (71, 'Gambia')
INTO Country (id, Name) VALUES (72, 'Georgia')
INTO Country (id, Name) VALUES (73, 'Ghana')
INTO Country (id, Name) VALUES (74, 'Granada')
INTO Country (id, Name) VALUES (75, 'Grecia')
INTO Country (id, Name) VALUES (76, 'Guatemala')
INTO Country (id, Name) VALUES (77, 'Guinea')
INTO Country (id, Name) VALUES (78, 'Guinea Ecuatorial')
INTO Country (id, Name) VALUES (79, 'Guinea-Bisáu')
INTO Country (id, Name) VALUES (80, 'Guyana')
INTO Country (id, Name) VALUES (81, 'Haití')
INTO Country (id, Name) VALUES (82, 'Honduras')
INTO Country (id, Name) VALUES (83, 'Hungría')
INTO Country (id, Name) VALUES (84, 'India')
INTO Country (id, Name) VALUES (85, 'Indonesia')
INTO Country (id, Name) VALUES (86, 'Irán')
INTO Country (id, Name) VALUES (87, 'Irak')
INTO Country (id, Name) VALUES (88, 'Irlanda')
INTO Country (id, Name) VALUES (89, 'Islandia')
INTO Country (id, Name) VALUES (90, 'Islas Marshall')
INTO Country (id, Name) VALUES (91, 'Islas Salomón')
INTO Country (id, Name) VALUES (92, 'Islas Vírgenes Británicas')
INTO Country (id, Name) VALUES (93, 'Islas Vírgenes de los Estados Unidos')
INTO Country (id, Name) VALUES (94, 'Israel')
INTO Country (id, Name) VALUES (95, 'Italia')
INTO Country (id, Name) VALUES (96, 'Jamaica')
INTO Country (id, Name) VALUES (97, 'Japón')
INTO Country (id, Name) VALUES (98, 'Jordania')
INTO Country (id, Name) VALUES (99, 'Kazajistán')
INTO Country (id, Name) VALUES (100, 'Kenia')
INTO Country (id, Name) VALUES (101, 'Kiribati')
INTO Country (id, Name) VALUES (102, 'Kuwait')
INTO Country (id, Name) VALUES (103, 'Kirguistán')
INTO Country (id, Name) VALUES (104, 'Laos')
INTO Country (id, Name) VALUES (105, 'Letonia')
INTO Country (id, Name) VALUES (106, 'Líbano')
INTO Country (id, Name) VALUES (107, 'Lesoto')
INTO Country (id, Name) VALUES (108, 'Liberia')
INTO Country (id, Name) VALUES (109, 'Libia')
INTO Country (id, Name) VALUES (110, 'Liechtenstein')
INTO Country (id, Name) VALUES (111, 'Lituania')
INTO Country (id, Name) VALUES (112, 'Luxemburgo')
INTO Country (id, Name) VALUES (113, 'Macedonia del Norte')
INTO Country (id, Name) VALUES (114, 'Madagascar')
INTO Country (id, Name) VALUES (115, 'Malaui')
INTO Country (id, Name) VALUES (116, 'Malasia')
INTO Country (id, Name) VALUES (117, 'Maldivas')
INTO Country (id, Name) VALUES (118, 'Malí')
INTO Country (id, Name) VALUES (119, 'Malta')
INTO Country (id, Name) VALUES (120, 'Marruecos')
INTO Country (id, Name) VALUES (121, 'Martinica')
INTO Country (id, Name) VALUES (122, 'Mauricio')
INTO Country (id, Name) VALUES (123, 'Mauritania')
INTO Country (id, Name) VALUES (124, 'Mayotte')
INTO Country (id, Name) VALUES (125, 'México')
INTO Country (id, Name) VALUES (126, 'Micronesia')
INTO Country (id, Name) VALUES (127, 'Moldavia')
INTO Country (id, Name) VALUES (128, 'Mónaco')
INTO Country (id, Name) VALUES (129, 'Mongolia')
INTO Country (id, Name) VALUES (130, 'Montenegro')
INTO Country (id, Name) VALUES (131, 'Montserrat')
INTO Country (id, Name) VALUES (132, 'Mozambique')
INTO Country (id, Name) VALUES (133, 'Namibia')
INTO Country (id, Name) VALUES (134, 'Nauru')
INTO Country (id, Name) VALUES (135, 'Nepal')
INTO Country (id, Name) VALUES (136, 'Nicaragua')
INTO Country (id, Name) VALUES (137, 'Níger')
INTO Country (id, Name) VALUES (138, 'Nigeria')
INTO Country (id, Name) VALUES (139, 'Niue')
INTO Country (id, Name) VALUES (140, 'Noruega')
INTO Country (id, Name) VALUES (141, 'Nueva Zelanda')
INTO Country (id, Name) VALUES (142, 'Omán')
INTO Country (id, Name) VALUES (143, 'Países Bajos')
INTO Country (id, Name) VALUES (144, 'Pakistán')
INTO Country (id, Name) VALUES (145, 'Palaos')
INTO Country (id, Name) VALUES (146, 'Panamá')
INTO Country (id, Name) VALUES (147, 'Papúa Nueva Guinea')
INTO Country (id, Name) VALUES (148, 'Paraguay')
INTO Country (id, Name) VALUES (149, 'Perú')
INTO Country (id, Name) VALUES (150, 'Polonia')
INTO Country (id, Name) VALUES (151, 'Portugal')
INTO Country (id, Name) VALUES (152, 'Reino Unido')
INTO Country (id, Name) VALUES (153, 'República Centroafricana')
INTO Country (id, Name) VALUES (154, 'República Checa')
INTO Country (id, Name) VALUES (155, 'República del Congo')
INTO Country (id, Name) VALUES (156, 'República Democrática del Congo')
INTO Country (id, Name) VALUES (157, 'República Dominicana')
INTO Country (id, Name) VALUES (158, 'República Sudafricana')
INTO Country (id, Name) VALUES (159, 'Ruanda')
INTO Country (id, Name) VALUES (160, 'Rumania')
INTO Country (id, Name) VALUES (161, 'Rusia')
INTO Country (id, Name) VALUES (162, 'Samoa')
INTO Country (id, Name) VALUES (163, 'San Cristóbal y Nieves')
INTO Country (id, Name) VALUES (164, 'San Marino')
INTO Country (id, Name) VALUES (165, 'San Vicente y las Granadinas')
INTO Country (id, Name) VALUES (166, 'Santa Lucía')
INTO Country (id, Name) VALUES (167, 'Santo Tomé y Príncipe')
INTO Country (id, Name) VALUES (168, 'Senegal')
INTO Country (id, Name) VALUES (169, 'Serbia')
INTO Country (id, Name) VALUES (170, 'Seychelles')
INTO Country (id, Name) VALUES (171, 'Sierra Leona')
INTO Country (id, Name) VALUES (172, 'Singapur')
INTO Country (id, Name) VALUES (173, 'Siria')
INTO Country (id, Name) VALUES (174, 'Somalia')
INTO Country (id, Name) VALUES (175, 'Sri Lanka')
INTO Country (id, Name) VALUES (176, 'Suazilandia')
INTO Country (id, Name) VALUES (177, 'Sudán')
INTO Country (id, Name) VALUES (178, 'Sudán del Sur')
INTO Country (id, Name) VALUES (179, 'Suecia')
INTO Country (id, Name) VALUES (180, 'Suiza')
INTO Country (id, Name) VALUES (181, 'Surinam')
INTO Country (id, Name) VALUES (182, 'Tailandia')
INTO Country (id, Name) VALUES (183, 'Taiwán')
INTO Country (id, Name) VALUES (184, 'Tanzania')
INTO Country (id, Name) VALUES (185, 'Tayikistán')
INTO Country (id, Name) VALUES (186, 'Timor Oriental')
INTO Country (id, Name) VALUES (187, 'Togo')
INTO Country (id, Name) VALUES (188, 'Tonga')
INTO Country (id, Name) VALUES (189, 'Trinidad y Tobago')
INTO Country (id, Name) VALUES (190, 'Túnez')
INTO Country (id, Name) VALUES (191, 'Turkmenistán')
INTO Country (id, Name) VALUES (192, 'Turquía')
INTO Country (id, Name) VALUES (193, 'Tuvalu')
INTO Country (id, Name) VALUES (194, 'Uganda')
INTO Country (id, Name) VALUES (195, 'Ucrania')
INTO Country (id, Name) VALUES (196, 'Uruguay')
INTO Country (id, Name) VALUES (197, 'Uzbekistán')
INTO Country (id, Name) VALUES (198, 'Vanuatu')
INTO Country (id, Name) VALUES (199, 'Venezuela')
INTO Country (id, Name) VALUES (200, 'Vietnam')
INTO Country (id, Name) VALUES (201, 'Yemen')
INTO Country (id, Name) VALUES (202, 'Yibuti')
INTO Country (id, Name) VALUES (203, 'Zambia')
INTO Country (id, Name) VALUES (204, 'Zimbabue')
SELECT 1 FROM dual;
COMMIT;
