/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Connect.ConnectDB;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import vista.InfoWindow;
import vista.loginWindow;
import vista.mainInterface;

/**
 *
 * @author Leo
 */

public class SigninWindow extends javax.swing.JFrame {

    /**
     * Creates new form loginWindow
     */
    // Variables containing new user data
    public String username, password, email, name, secondName, lastNames, secondLastNames, address, birthdate, 
                  gender ,idType, nationality, country, region, district;
    public int phone, idNum, realgender, realidtype, realidDistrict, realidnationality;
    public Date realBirthdate;
    // Do not touch uwu
    public java.awt.Container mainContainer;
    public java.awt.CardLayout mainLayout;
    
    public boolean userExists(String Username) throws SQLException
    {
        if (!ConnectDB.checkUsernameAvailability(username)){
        return true;
        } else{
            return false;
        }
    }
    
    public void registerNewUser()
    {
        return;
    }

    
    public SigninWindow() {
        initComponents();
        mainContainer = getContentPane();
        mainLayout = (java.awt.CardLayout) mainContainer.getLayout();
        
        try {
            ArrayList<String> genders = ConnectDB.getGender();
            for (String gender : genders) {
                genderCB.addItem(gender);
            }
            ArrayList<String> idType = ConnectDB.getIdtype();
            for (String id : idType) {
                idTypeCB.addItem(id);
        }
            ArrayList<String> Nationalities = ConnectDB.getNationality();
            for (String country : Nationalities) {
                 nationCB.addItem(country);
            }
            ArrayList<String> Countries = ConnectDB.getCountry();
            for (String country : Countries) {
                countryCB.addItem(country);
            }
            countryCB.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Limpiar los elementos actuales del ComboBox 6
                    regionCB.removeAllItems();

                    // Obtener el elemento seleccionado por el usuario
                    country = (String) countryCB.getSelectedItem();
                    System.out.println(country);
                    try {
                        ArrayList<String> States = ConnectDB.getStates(country);
                                for (String state : States) {
                                    regionCB.addItem(state);
                                }
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }
            });

            regionCB.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Limpiar los elementos actuales del ComboBox 6
                    districtCB.removeAllItems();

                    // Obtener el elemento seleccionado por el usuario
                    region = (String) regionCB.getSelectedItem();
                    System.out.println(region);
                    try {
                        ArrayList<String> districts = ConnectDB.getDistricts(region);
                        for (String district : districts) {
                            districtCB.addItem(district);
                        }
                        System.out.println("" + districts);
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }
            });
            
        } catch (SQLException ex) {
            Logger.getLogger(InfoWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userSigninP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        next1Bttn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        confirmTxt = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cancel1Bttn1 = new javax.swing.JButton();
        idNumberTxt = new javax.swing.JTextField();
        idTypeCB = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        infoSigninP = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        next2Bttn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lastNamesTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        genderCB = new javax.swing.JComboBox<>();
        birthdateFormattedTxt = new javax.swing.JFormattedTextField();
        backBttn1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        secondNameTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        secondSurnameTxt = new javax.swing.JTextField();
        addressSigninP = new javax.swing.JPanel();
        finishBttn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nationCB = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTxt = new javax.swing.JTextArea();
        countryCB = new javax.swing.JComboBox<>();
        regionCB = new javax.swing.JComboBox<>();
        districtCB = new javax.swing.JComboBox<>();
        backBttn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sign in Window");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        userSigninP.setBackground(new java.awt.Color(48, 89, 138));

        jLabel1.setBackground(new java.awt.Color(210, 235, 255));
        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(210, 235, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Username");

        usernameTxt.setBackground(new java.awt.Color(237, 204, 111));
        usernameTxt.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        usernameTxt.setForeground(new java.awt.Color(48, 89, 138));
        usernameTxt.setToolTipText("");
        usernameTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));

        jLabel2.setBackground(new java.awt.Color(210, 235, 255));
        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(210, 235, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Password");

        passwordTxt.setBackground(new java.awt.Color(237, 204, 111));
        passwordTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(48, 89, 138));
        passwordTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));

        next1Bttn.setBackground(new java.awt.Color(237, 204, 111));
        next1Bttn.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        next1Bttn.setForeground(new java.awt.Color(48, 89, 138));
        next1Bttn.setText("Next");
        next1Bttn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));
        next1Bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1BttnActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(210, 235, 255));
        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(210, 235, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Confirm password");

        confirmTxt.setBackground(new java.awt.Color(237, 204, 111));
        confirmTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmTxt.setForeground(new java.awt.Color(48, 89, 138));
        confirmTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));

        jLabel4.setBackground(new java.awt.Color(210, 235, 255));
        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(210, 235, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("E-mail address");

        emailTxt.setBackground(new java.awt.Color(237, 204, 111));
        emailTxt.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(48, 89, 138));
        emailTxt.setToolTipText("");
        emailTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));

        jLabel5.setBackground(new java.awt.Color(210, 235, 255));
        jLabel5.setFont(new java.awt.Font("Gadugi", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(48, 89, 138));
        jLabel5.setText("Passwords do not match ");

        cancel1Bttn1.setBackground(new java.awt.Color(237, 204, 111));
        cancel1Bttn1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        cancel1Bttn1.setForeground(new java.awt.Color(48, 89, 138));
        cancel1Bttn1.setText("Cancel");
        cancel1Bttn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));
        cancel1Bttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1Bttn1ActionPerformed(evt);
            }
        });

        idNumberTxt.setBackground(new java.awt.Color(237, 204, 111));
        idNumberTxt.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        idNumberTxt.setForeground(new java.awt.Color(48, 89, 138));
        idNumberTxt.setToolTipText("");
        idNumberTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));
        idNumberTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idNumberTxtFocusGained(evt);
            }
        });

        idTypeCB.setBackground(new java.awt.Color(237, 204, 111));
        idTypeCB.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        idTypeCB.setForeground(new java.awt.Color(48, 89, 138));
        idTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        idTypeCB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));

        jLabel9.setBackground(new java.awt.Color(210, 235, 255));
        jLabel9.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(210, 235, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Id type");

        jLabel8.setBackground(new java.awt.Color(210, 235, 255));
        jLabel8.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(210, 235, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Id number");

        javax.swing.GroupLayout userSigninPLayout = new javax.swing.GroupLayout(userSigninP);
        userSigninP.setLayout(userSigninPLayout);
        userSigninPLayout.setHorizontalGroup(
            userSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userSigninPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usernameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(userSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordTxt))
                    .addComponent(next1Bttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(userSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(userSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(userSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmTxt)))
                    .addComponent(cancel1Bttn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(userSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idTypeCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(userSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idNumberTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                .addContainerGap())
        );
        userSigninPLayout.setVerticalGroup(
            userSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userSigninPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTypeCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(next1Bttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel1Bttn1)
                .addContainerGap())
        );

        getContentPane().add(userSigninP, "card2");

        infoSigninP.setBackground(new java.awt.Color(48, 89, 138));

        jLabel6.setBackground(new java.awt.Color(210, 235, 255));
        jLabel6.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(210, 235, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Name");

        nameTxt.setBackground(new java.awt.Color(237, 204, 111));
        nameTxt.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(48, 89, 138));
        nameTxt.setToolTipText("");
        nameTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));
        nameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTxtFocusGained(evt);
            }
        });

        next2Bttn.setBackground(new java.awt.Color(237, 204, 111));
        next2Bttn.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        next2Bttn.setForeground(new java.awt.Color(48, 89, 138));
        next2Bttn.setText("Next");
        next2Bttn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));
        next2Bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next2BttnActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(210, 235, 255));
        jLabel7.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(210, 235, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Surname");

        lastNamesTxt.setBackground(new java.awt.Color(237, 204, 111));
        lastNamesTxt.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        lastNamesTxt.setForeground(new java.awt.Color(48, 89, 138));
        lastNamesTxt.setToolTipText("");
        lastNamesTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));
        lastNamesTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNamesTxtFocusGained(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(210, 235, 255));
        jLabel10.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(210, 235, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Phone number");

        phoneTxt.setBackground(new java.awt.Color(237, 204, 111));
        phoneTxt.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        phoneTxt.setForeground(new java.awt.Color(48, 89, 138));
        phoneTxt.setToolTipText("");
        phoneTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));
        phoneTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneTxtFocusGained(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(210, 235, 255));
        jLabel11.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(210, 235, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Birthdate");

        jLabel12.setBackground(new java.awt.Color(210, 235, 255));
        jLabel12.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(210, 235, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Gender");

        genderCB.setBackground(new java.awt.Color(237, 204, 111));
        genderCB.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        genderCB.setForeground(new java.awt.Color(48, 89, 138));
        genderCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        genderCB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));
        genderCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderCBActionPerformed(evt);
            }
        });

        birthdateFormattedTxt.setBackground(new java.awt.Color(237, 204, 111));
        birthdateFormattedTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));
        birthdateFormattedTxt.setForeground(new java.awt.Color(48, 89, 138));
        birthdateFormattedTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        birthdateFormattedTxt.setToolTipText("DD/MM/YYYY");
        birthdateFormattedTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                birthdateFormattedTxtFocusGained(evt);
            }
        });

        backBttn1.setBackground(new java.awt.Color(237, 204, 111));
        backBttn1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        backBttn1.setForeground(new java.awt.Color(48, 89, 138));
        backBttn1.setText("Back");
        backBttn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));
        backBttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttn1ActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(210, 235, 255));
        jLabel18.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(210, 235, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel18.setText("Second Name");

        secondNameTxt.setBackground(new java.awt.Color(237, 204, 111));
        secondNameTxt.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        secondNameTxt.setForeground(new java.awt.Color(48, 89, 138));
        secondNameTxt.setToolTipText("");
        secondNameTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));
        secondNameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                secondNameTxtFocusGained(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(210, 235, 255));
        jLabel19.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(210, 235, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText("Second Surname");

        secondSurnameTxt.setBackground(new java.awt.Color(237, 204, 111));
        secondSurnameTxt.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        secondSurnameTxt.setForeground(new java.awt.Color(48, 89, 138));
        secondSurnameTxt.setToolTipText("");
        secondSurnameTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));
        secondSurnameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                secondSurnameTxtFocusGained(evt);
            }
        });

        javax.swing.GroupLayout infoSigninPLayout = new javax.swing.GroupLayout(infoSigninP);
        infoSigninP.setLayout(infoSigninPLayout);
        infoSigninPLayout.setHorizontalGroup(
            infoSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoSigninPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addComponent(next2Bttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(infoSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastNamesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(infoSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(birthdateFormattedTxt))
                    .addGroup(infoSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phoneTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(genderCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(backBttn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(secondNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(infoSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(secondSurnameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                .addContainerGap())
        );
        infoSigninPLayout.setVerticalGroup(
            infoSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoSigninPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(secondNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastNamesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(secondSurnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genderCB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(birthdateFormattedTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(next2Bttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBttn1)
                .addContainerGap())
        );

        getContentPane().add(infoSigninP, "card3");

        addressSigninP.setBackground(new java.awt.Color(48, 89, 138));

        finishBttn.setBackground(new java.awt.Color(237, 204, 111));
        finishBttn.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        finishBttn.setForeground(new java.awt.Color(48, 89, 138));
        finishBttn.setText("Finish");
        finishBttn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));
        finishBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBttnActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(210, 235, 255));
        jLabel13.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(210, 235, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Nationality");

        jLabel14.setBackground(new java.awt.Color(210, 235, 255));
        jLabel14.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(210, 235, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText("Country");

        nationCB.setBackground(new java.awt.Color(237, 204, 111));
        nationCB.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        nationCB.setForeground(new java.awt.Color(48, 89, 138));
        nationCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        nationCB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));

        jLabel15.setBackground(new java.awt.Color(210, 235, 255));
        jLabel15.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(210, 235, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("Region");

        jLabel16.setBackground(new java.awt.Color(210, 235, 255));
        jLabel16.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(210, 235, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("District");

        jLabel17.setBackground(new java.awt.Color(210, 235, 255));
        jLabel17.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(210, 235, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText("Address");

        addressTxt.setBackground(new java.awt.Color(237, 204, 111));
        addressTxt.setColumns(20);
        addressTxt.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        addressTxt.setForeground(new java.awt.Color(48, 89, 138));
        addressTxt.setLineWrap(true);
        addressTxt.setRows(5);
        addressTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));
        addressTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressTxtFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(addressTxt);

        countryCB.setBackground(new java.awt.Color(237, 204, 111));
        countryCB.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        countryCB.setForeground(new java.awt.Color(48, 89, 138));
        countryCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        countryCB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));

        regionCB.setBackground(new java.awt.Color(237, 204, 111));
        regionCB.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        regionCB.setForeground(new java.awt.Color(48, 89, 138));
        regionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        regionCB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));

        districtCB.setBackground(new java.awt.Color(237, 204, 111));
        districtCB.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        districtCB.setForeground(new java.awt.Color(48, 89, 138));
        districtCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        districtCB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));

        backBttn2.setBackground(new java.awt.Color(237, 204, 111));
        backBttn2.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        backBttn2.setForeground(new java.awt.Color(48, 89, 138));
        backBttn2.setText("Back");
        backBttn2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 235, 255), 4, true));
        backBttn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addressSigninPLayout = new javax.swing.GroupLayout(addressSigninP);
        addressSigninP.setLayout(addressSigninPLayout);
        addressSigninPLayout.setHorizontalGroup(
            addressSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressSigninPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finishBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addressSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nationCB, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addressSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(districtCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(backBttn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addressSigninPLayout.createSequentialGroup()
                        .addGroup(addressSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addressSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regionCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(countryCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(addressSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addressSigninPLayout.setVerticalGroup(
            addressSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressSigninPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addressSigninPLayout.createSequentialGroup()
                        .addGroup(addressSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nationCB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addressSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countryCB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(regionCB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addressSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(districtCB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addressSigninPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addressSigninPLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBttn2)
                .addContainerGap())
        );

        getContentPane().add(addressSigninP, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.setVisible(false);
        new mainInterface().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        new mainInterface().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void next1BttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1BttnActionPerformed
        // Checks if passwords are the same, if not, displays error message
        try {
            idNum = Integer.parseInt(idNumberTxt.getText());
        } catch (Exception e) {
            idNumberTxt.setText("Id Number field must be filled");
        }
        if(!passwordTxt.getText().equals(confirmTxt.getText()))
        {
            jLabel5.setForeground(new java.awt.Color(226,122,55));
            jLabel5.setText("Passwords do not match ");
        } else if(passwordTxt.getText().equals("")
            || usernameTxt.getText().equals("")
            || emailTxt.getText().equals("")
            || idNumberTxt.getText().equals("")
            || idNumberTxt.getText().equals("Id Number field must be filled"))
        {
            jLabel5.setForeground(new java.awt.Color(226,122,55));
            jLabel5.setText("No field can be left empty ");
        }
        try{
            if(userExists(usernameTxt.getText())) // TODO: Function userExists
            {
                jLabel5.setForeground(new java.awt.Color(226,122,55));
                jLabel5.setText("Username already taken ");
                username = "";
            } 
        } catch (Exception e) {
            jLabel5.setForeground(new java.awt.Color(226,122,55));
                jLabel5.setText("Username already taken ");
        }
        // The data is valid, and can be stored
        username = usernameTxt.getText();
        if(!username.equals(""))
        {
            jLabel5.setForeground(new java.awt.Color(48, 89, 138));
            password = passwordTxt.getText();
            email = emailTxt.getText();
            mainLayout.next(mainContainer);
        }
    }//GEN-LAST:event_next1BttnActionPerformed

    private void cancel1Bttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1Bttn1ActionPerformed
        this.setVisible(false);
        new mainInterface().setVisible(true);
    }//GEN-LAST:event_cancel1Bttn1ActionPerformed

    private void idNumberTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idNumberTxtFocusGained
        if(idNumberTxt.getText().equals("Id Number field must be filled"))
        {
            idNumberTxt.setText("");
        }
    }//GEN-LAST:event_idNumberTxtFocusGained

    private void nameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTxtFocusGained
        if(nameTxt.getText().equals("Name field must be filled"))
        {
            nameTxt.setText("");
        }
    }//GEN-LAST:event_nameTxtFocusGained

    private void next2BttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next2BttnActionPerformed
        if(birthdateFormattedTxt.getText().equals(""))
        {
            birthdateFormattedTxt.setText("Plz date");
        }
        if(nameTxt.getText().equals(""))
        {
            nameTxt.setText("Name field must be filled");
        }
        if(lastNamesTxt.getText().equals(""))
        {
            lastNamesTxt.setText("Lastnames field must be filled");
        }
        if(phoneTxt.getText().equals(""))
        {
            phoneTxt.setText("Phone field must be filled");
        }
        if(!nameTxt.getText().contains("must be filled")
            && !lastNamesTxt.getText().contains("must be filled")
            && !phoneTxt.getText().contains("must be filled")
            && !idNumberTxt.getText().contains("must be filled")
            && !birthdateFormattedTxt.getText().contains("Plz"))
        {
            name = nameTxt.getText();
            secondName = secondNameTxt.getText();
            lastNames = lastNamesTxt.getText();
            secondLastNames = secondSurnameTxt.getText();
            birthdate = birthdateFormattedTxt.getText();
            gender = (String)genderCB.getSelectedItem();
            idType = (String)idTypeCB.getSelectedItem();
            
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            try {
                realBirthdate = dateFormat.parse(birthdate);
            } catch (ParseException ex) {
                Logger.getLogger(SigninWindow.class.getName()).log(Level.SEVERE, null, ex);
            }

            realgender = (int) genderCB.getSelectedIndex();
            realgender = realgender + 1;
            System.out.println("el genero es" + realgender);

            realidtype = (int) idTypeCB.getSelectedIndex();
            realidtype = realidtype + 1;
            System.out.println("el tipo es" + realidtype);
            
            try {
                phone = Integer.parseInt(phoneTxt.getText());
            } catch (Exception e) {
                phoneTxt.setText("Phone field must be filled");
            }
            if(!phoneTxt.getText().contains("must be filled")
                && !idNumberTxt.getText().contains("must be filled"))
            {
                mainLayout.next(mainContainer);
            }
        }
    }//GEN-LAST:event_next2BttnActionPerformed

    private void lastNamesTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNamesTxtFocusGained
        if(lastNamesTxt.getText().equals("Lastnames field must be filled"))
        {
            lastNamesTxt.setText("");
        }
    }//GEN-LAST:event_lastNamesTxtFocusGained

    private void phoneTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneTxtFocusGained
        if(phoneTxt.getText().equals("Phone field must be filled"))
        {
            phoneTxt.setText("");
        }
    }//GEN-LAST:event_phoneTxtFocusGained

    private void birthdateFormattedTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_birthdateFormattedTxtFocusGained
        if(birthdateFormattedTxt.getText().equals("Plz date"))
        {
            birthdateFormattedTxt.setText("DD/MM/YYYY");
        }
    }//GEN-LAST:event_birthdateFormattedTxtFocusGained

    private void backBttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttn1ActionPerformed
        mainLayout.previous(mainContainer);
    }//GEN-LAST:event_backBttn1ActionPerformed

    private void secondNameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_secondNameTxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_secondNameTxtFocusGained

    private void secondSurnameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_secondSurnameTxtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_secondSurnameTxtFocusGained

    private void finishBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBttnActionPerformed
        if(addressTxt.getText().equals(""))
        {
            addressTxt.setText("Address must be provided");
        } else {
            nationality = (String) nationCB.getSelectedItem();
            country = (String) countryCB.getSelectedItem();
            region = (String) regionCB.getSelectedItem();
            district = (String) districtCB.getSelectedItem();
            address = addressTxt.getText();
           
           realidDistrict = (int) districtCB.getSelectedIndex();
           realidDistrict = realidDistrict + 1;
           System.out.println("La distrito es" + realidDistrict);

           realidnationality = (int) nationCB.getSelectedIndex();
           realidnationality = realidnationality + 1;
           System.out.println("La nacionanlidad es" + realidnationality);
           

        try {
            ConnectDB.InsertUserSys(name, secondName, lastNames, secondLastNames, idNum, null, email, phone, username, password,
                    realidDistrict, realidnationality, realgender, realidtype);
        } catch (SQLException ex) {
            Logger.getLogger(SigninWindow.class.getName()).log(Level.SEVERE, null, ex);
            System.err.println("Error al insertar el usuario en la base de datos: " + ex.getMessage());
        }       
            this.setVisible(false);
            new loginWindow().setVisible(true);
        }
    }//GEN-LAST:event_finishBttnActionPerformed

    private void addressTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTxtFocusGained
        if(addressTxt.getText().equals("Address must be provided"))
        {
            addressTxt.setText("");
        }
    }//GEN-LAST:event_addressTxtFocusGained

    private void backBttn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttn2ActionPerformed
        mainLayout.previous(mainContainer);
    }//GEN-LAST:event_backBttn2ActionPerformed

    private void genderCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SigninWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SigninWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SigninWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SigninWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SigninWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addressSigninP;
    private javax.swing.JTextArea addressTxt;
    private javax.swing.JButton backBttn1;
    private javax.swing.JButton backBttn2;
    private javax.swing.JFormattedTextField birthdateFormattedTxt;
    private javax.swing.JButton cancel1Bttn1;
    private javax.swing.JPasswordField confirmTxt;
    private javax.swing.JComboBox<String> countryCB;
    private javax.swing.JComboBox<String> districtCB;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JButton finishBttn;
    private javax.swing.JComboBox<String> genderCB;
    private javax.swing.JTextField idNumberTxt;
    private javax.swing.JComboBox<String> idTypeCB;
    private javax.swing.JPanel infoSigninP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNamesTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JComboBox<String> nationCB;
    private javax.swing.JButton next1Bttn;
    private javax.swing.JButton next2Bttn;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JComboBox<String> regionCB;
    private javax.swing.JTextField secondNameTxt;
    private javax.swing.JTextField secondSurnameTxt;
    private javax.swing.JPanel userSigninP;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
