/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import Connect.ConnectDB;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Leo
 */
public class InfoWindow extends javax.swing.JFrame {
    String selectedGender;
    String selectedidType;

    /**
     * Creates new form loginWindow
     */
    public InfoWindow() {
        initComponents();
        // Llena el combo box con las opciones de género al iniciar la ventana
        try {
            ArrayList<String> genders = ConnectDB.getGender();
            for (String gender : genders) {
                jComboBox1.addItem(gender);
            }
            jComboBox1.addActionListener(new ActionListener(){
               @Override
                // Obtener el elemento seleccionado por el usuario
                public void actionPerformed(ActionEvent e){     
                    selectedGender = (String) jComboBox1.getSelectedItem();
            }}
            );
            ArrayList<String> idType = ConnectDB.getIdtype();
            for (String id : idType) {
                jComboBox4.addItem(id);
        }
            jComboBox4.addActionListener(new ActionListener(){
               @Override
                // Obtener el elemento seleccionado por el usuario
                public void actionPerformed(ActionEvent e){     
                    selectedidType = (String) jComboBox4.getSelectedItem();
            }}
            );
        
        
        } catch (SQLException ex) {
            Logger.getLogger(InfoWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userEditorUsername = new javax.swing.JTextField();
        userEditorEmail = new javax.swing.JTextField();
        userEditorPassword = new javax.swing.JPasswordField();
        userEditorPasswordConf = new javax.swing.JPasswordField();
        userEditorName = new javax.swing.JTextField();
        userEditorSecondName = new javax.swing.JTextField();
        userEditorSurname = new javax.swing.JTextField();
        userEditorSecondSurname = new javax.swing.JTextField();
        userEditorPhone = new javax.swing.JTextField();
        userEditorIdNum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign in Window");
        setResizable(false);

        userEditorUsername.setBackground(new java.awt.Color(254, 249, 217));
        userEditorUsername.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        userEditorUsername.setForeground(new java.awt.Color(68, 51, 41));
        userEditorUsername.setToolTipText("");
        userEditorUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201, 198, 145), 4));

        userEditorEmail.setBackground(new java.awt.Color(254, 249, 217));
        userEditorEmail.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        userEditorEmail.setForeground(new java.awt.Color(68, 51, 41));
        userEditorEmail.setToolTipText("");
        userEditorEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201, 198, 145), 4));

        userEditorPassword.setBackground(new java.awt.Color(254, 249, 217));
        userEditorPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userEditorPassword.setForeground(new java.awt.Color(68, 51, 41));
        userEditorPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201, 198, 145), 4));

        userEditorPasswordConf.setBackground(new java.awt.Color(254, 249, 217));
        userEditorPasswordConf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userEditorPasswordConf.setForeground(new java.awt.Color(68, 51, 41));
        userEditorPasswordConf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201, 198, 145), 4));

        userEditorName.setBackground(new java.awt.Color(254, 249, 217));
        userEditorName.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        userEditorName.setForeground(new java.awt.Color(201, 198, 145));
        userEditorName.setToolTipText("");
        userEditorName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201, 198, 145), 4));

        userEditorSecondName.setBackground(new java.awt.Color(254, 249, 217));
        userEditorSecondName.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        userEditorSecondName.setForeground(new java.awt.Color(201, 198, 145));
        userEditorSecondName.setToolTipText("");
        userEditorSecondName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201, 198, 145), 4));

        userEditorSurname.setBackground(new java.awt.Color(254, 249, 217));
        userEditorSurname.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        userEditorSurname.setForeground(new java.awt.Color(201, 198, 145));
        userEditorSurname.setToolTipText("");
        userEditorSurname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201, 198, 145), 4));

        userEditorSecondSurname.setBackground(new java.awt.Color(254, 249, 217));
        userEditorSecondSurname.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        userEditorSecondSurname.setForeground(new java.awt.Color(201, 198, 145));
        userEditorSecondSurname.setToolTipText("");
        userEditorSecondSurname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201, 198, 145), 4));

        userEditorPhone.setBackground(new java.awt.Color(254, 249, 217));
        userEditorPhone.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        userEditorPhone.setForeground(new java.awt.Color(201, 198, 145));
        userEditorPhone.setToolTipText("");
        userEditorPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201, 198, 145), 4));

        userEditorIdNum.setBackground(new java.awt.Color(254, 249, 217));
        userEditorIdNum.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        userEditorIdNum.setForeground(new java.awt.Color(201, 198, 145));
        userEditorIdNum.setToolTipText("");
        userEditorIdNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201, 198, 145), 4));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(userEditorSecondSurname)
                        .addComponent(userEditorIdNum)
                        .addComponent(userEditorPasswordConf)
                        .addComponent(userEditorPassword)
                        .addComponent(userEditorUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userEditorEmail)
                        .addComponent(userEditorPhone)
                        .addComponent(userEditorName)
                        .addComponent(userEditorSecondName)
                        .addComponent(userEditorSurname))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(userEditorUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(userEditorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(userEditorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(userEditorPasswordConf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(userEditorName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(userEditorSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(userEditorSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(userEditorSecondSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE)
                    .addComponent(userEditorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(45, 45, 45)
                    .addComponent(userEditorIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField userEditorEmail;
    private javax.swing.JTextField userEditorIdNum;
    private javax.swing.JTextField userEditorName;
    private javax.swing.JPasswordField userEditorPassword;
    private javax.swing.JPasswordField userEditorPasswordConf;
    private javax.swing.JTextField userEditorPhone;
    private javax.swing.JTextField userEditorSecondName;
    private javax.swing.JTextField userEditorSecondSurname;
    private javax.swing.JTextField userEditorSurname;
    private javax.swing.JTextField userEditorUsername;
    // End of variables declaration//GEN-END:variables
}

