INSERT ALL
INTO Nationality (id, Name) VALUES (1, 'Afganistan')
INTO Nationality (id, Name) VALUES (2, 'Albania')
INTO Nationality (id, Name) VALUES (3, 'Alemania')
INTO Nationality (id, Name) VALUES (4, 'Andorra')
INTO Nationality (id, Name) VALUES (5, 'Angola')
INTO Nationality (id, Name) VALUES (6, 'Antigua y Barbuda')
INTO Nationality (id, Name) VALUES (7, 'Arabia Saudita')
INTO Nationality (id, Name) VALUES (8, 'Argelia')
INTO Nationality (id, Name) VALUES (9, 'Argentina')
INTO Nationality (id, Name) VALUES (10, 'Armenia')
INTO Nationality (id, Name) VALUES (11, 'Australia')
INTO Nationality (id, Name) VALUES (12, 'Austria')
INTO Nationality (id, Name) VALUES (13, 'Azerbaiyán')
INTO Nationality (id, Name) VALUES (14, 'Bahamas')
INTO Nationality (id, Name) VALUES (15, 'Bangladés')
INTO Nationality (id, Name) VALUES (16, 'Barbados')
INTO Nationality (id, Name) VALUES (17, 'Baréin')
INTO Nationality (id, Name) VALUES (18, 'Bélgica')
INTO Nationality (id, Name) VALUES (19, 'Belice')
INTO Nationality (id, Name) VALUES (20, 'Benín')
INTO Nationality (id, Name) VALUES (21, 'Bielorrusia')
INTO Nationality (id, Name) VALUES (22, 'Birmania')
INTO Nationality (id, Name) VALUES (23, 'Bolivia')
INTO Nationality (id, Name) VALUES (24, 'Bosnia y Herzegovina')
INTO Nationality (id, Name) VALUES (25, 'Botsuana')
INTO Nationality (id, Name) VALUES (26, 'Brasil')
INTO Nationality (id, Name) VALUES (27, 'Bulgaria')
INTO Nationality (id, Name) VALUES (28, 'Burkina Faso')
INTO Nationality (id, Name) VALUES (29, 'Burundi')
INTO Nationality (id, Name) VALUES (30, 'Bután')
INTO Nationality (id, Name) VALUES (31, 'Cabo Verde')
INTO Nationality (id, Name) VALUES (32, 'Camboya')
INTO Nationality (id, Name) VALUES (33, 'Camerún')
INTO Nationality (id, Name) VALUES (34, 'Canadá')
INTO Nationality (id, Name) VALUES (35, 'Catar')
INTO Nationality (id, Name) VALUES (36, 'Chad')
INTO Nationality (id, Name) VALUES (37, 'Chile')
INTO Nationality (id, Name) VALUES (38, 'China')
INTO Nationality (id, Name) VALUES (39, 'Chipre')
INTO Nationality (id, Name) VALUES (40, 'Ciudad del Vaticano')
INTO Nationality (id, Name) VALUES (41, 'Colombia')
INTO Nationality (id, Name) VALUES (42, 'Comoras')
INTO Nationality (id, Name) VALUES (43, 'Congo')
INTO Nationality (id, Name) VALUES (44, 'Corea del Norte')
INTO Nationality (id, Name) VALUES (45, 'Corea del Sur')
INTO Nationality (id, Name) VALUES (46, 'Costa de Marfil')
INTO Nationality (id, Name) VALUES (47, 'Costa Rica')
INTO Nationality (id, Name) VALUES (48, 'Croacia')
INTO Nationality (id, Name) VALUES (49, 'Cuba')
INTO Nationality (id, Name) VALUES (50, 'Curazao')
INTO Nationality (id, Name) VALUES (51, 'Chipre del Norte')
INTO Nationality (id, Name) VALUES (52, 'Dinamarca')
INTO Nationality (id, Name) VALUES (53, 'Dominica')
INTO Nationality (id, Name) VALUES (54, 'Ecuador')
INTO Nationality (id, Name) VALUES (55, 'Egipto')
INTO Nationality (id, Name) VALUES (56, 'El Salvador')
INTO Nationality (id, Name) VALUES (57, 'Emiratos Árabes Unidos')
INTO Nationality (id, Name) VALUES (58, 'Eritrea')
INTO Nationality (id, Name) VALUES (59, 'Eslovaquia')
INTO Nationality (id, Name) VALUES (60, 'Eslovenia')
INTO Nationality (id, Name) VALUES (61, 'España')
INTO Nationality (id, Name) VALUES (62, 'Estados Unidos')
INTO Nationality (id, Name) VALUES (63, 'Estonia')
INTO Nationality (id, Name) VALUES (64, 'Eswatini')
INTO Nationality (id, Name) VALUES (65, 'Etiopía')
INTO Nationality (id, Name) VALUES (66, 'Filipinas')
INTO Nationality (id, Name) VALUES (67, 'Finlandia')
INTO Nationality (id, Name) VALUES (68, 'Fiyi')
INTO Nationality (id, Name) VALUES (69, 'Francia')
INTO Nationality (id, Name) VALUES (70, 'Gabón')
INTO Nationality (id, Name) VALUES (71, 'Gambia')
INTO Nationality (id, Name) VALUES (72, 'Georgia')
INTO Nationality (id, Name) VALUES (73, 'Ghana')
INTO Nationality (id, Name) VALUES (74, 'Granada')
INTO Nationality (id, Name) VALUES (75, 'Grecia')
INTO Nationality (id, Name) VALUES (76, 'Guatemala')
INTO Nationality (id, Name) VALUES (77, 'Guinea')
INTO Nationality (id, Name) VALUES (78, 'Guinea Ecuatorial')
INTO Nationality (id, Name) VALUES (79, 'Guinea-Bisáu')
INTO Nationality (id, Name) VALUES (80, 'Guyana')
INTO Nationality (id, Name) VALUES (81, 'Haití')
INTO Nationality (id, Name) VALUES (82, 'Honduras')
INTO Nationality (id, Name) VALUES (83, 'Hungría')
INTO Nationality (id, Name) VALUES (84, 'India')
INTO Nationality (id, Name) VALUES (85, 'Indonesia')
INTO Nationality (id, Name) VALUES (86, 'Irán')
INTO Nationality (id, Name) VALUES (87, 'Irak')
INTO Nationality (id, Name) VALUES (88, 'Irlanda')
INTO Nationality (id, Name) VALUES (89, 'Islandia')
INTO Nationality (id, Name) VALUES (90, 'Islas Marshall')
INTO Nationality (id, Name) VALUES (91, 'Islas Salomón')
INTO Nationality (id, Name) VALUES (92, 'Islas Vírgenes Británicas')
INTO Nationality (id, Name) VALUES (93, 'Islas Vírgenes de los Estados Unidos')
INTO Nationality (id, Name) VALUES (94, 'Israel')
INTO Nationality (id, Name) VALUES (95, 'Italia')
INTO Nationality (id, Name) VALUES (96, 'Jamaica')
INTO Nationality (id, Name) VALUES (97, 'Japón')
INTO Nationality (id, Name) VALUES (98, 'Jordania')
INTO Nationality (id, Name) VALUES (99, 'Kazajistán')
INTO Nationality (id, Name) VALUES (100, 'Kenia')
INTO Nationality (id, Name) VALUES (101, 'Kiribati')
INTO Nationality (id, Name) VALUES (102, 'Kuwait')
INTO Nationality (id, Name) VALUES (103, 'Kirguistán')
INTO Nationality (id, Name) VALUES (104, 'Laos')
INTO Nationality (id, Name) VALUES (105, 'Letonia')
INTO Nationality (id, Name) VALUES (106, 'Líbano')
INTO Nationality (id, Name) VALUES (107, 'Lesoto')
INTO Nationality (id, Name) VALUES (108, 'Liberia')
INTO Nationality (id, Name) VALUES (109, 'Libia')
INTO Nationality (id, Name) VALUES (110, 'Liechtenstein')
INTO Nationality (id, Name) VALUES (111, 'Lituania')
INTO Nationality (id, Name) VALUES (112, 'Luxemburgo')
INTO Nationality (id, Name) VALUES (113, 'Macedonia del Norte')
INTO Nationality (id, Name) VALUES (114, 'Madagascar')
INTO Nationality (id, Name) VALUES (115, 'Malaui')
INTO Nationality (id, Name) VALUES (116, 'Malasia')
INTO Nationality (id, Name) VALUES (117, 'Maldivas')
INTO Nationality (id, Name) VALUES (118, 'Malí')
INTO Nationality (id, Name) VALUES (119, 'Malta')
INTO Nationality (id, Name) VALUES (120, 'Marruecos')
INTO Nationality (id, Name) VALUES (121, 'Martinica')
INTO Nationality (id, Name) VALUES (122, 'Mauricio')
INTO Nationality (id, Name) VALUES (123, 'Mauritania')
INTO Nationality (id, Name) VALUES (124, 'Mayotte')
INTO Nationality (id, Name) VALUES (125, 'México')
INTO Nationality (id, Name) VALUES (126, 'Micronesia')
INTO Nationality (id, Name) VALUES (127, 'Moldavia')
INTO Nationality (id, Name) VALUES (128, 'Mónaco')
INTO Nationality (id, Name) VALUES (129, 'Mongolia')
INTO Nationality (id, Name) VALUES (130, 'Montenegro')
INTO Nationality (id, Name) VALUES (131, 'Montserrat')
INTO Nationality (id, Name) VALUES (132, 'Mozambique')
INTO Nationality (id, Name) VALUES (133, 'Namibia')
INTO Nationality (id, Name) VALUES (134, 'Nauru')
INTO Nationality (id, Name) VALUES (135, 'Nepal')
INTO Nationality (id, Name) VALUES (136, 'Nicaragua')
INTO Nationality (id, Name) VALUES (137, 'Níger')
INTO Nationality (id, Name) VALUES (138, 'Nigeria')
INTO Nationality (id, Name) VALUES (139, 'Niue')
INTO Nationality (id, Name) VALUES (140, 'Noruega')
INTO Nationality (id, Name) VALUES (141, 'Nueva Zelanda')
INTO Nationality (id, Name) VALUES (142, 'Omán')
INTO Nationality (id, Name) VALUES (143, 'Países Bajos')
INTO Nationality (id, Name) VALUES (144, 'Pakistán')
INTO Nationality (id, Name) VALUES (145, 'Palaos')
INTO Nationality (id, Name) VALUES (146, 'Panamá')
INTO Nationality (id, Name) VALUES (147, 'Papúa Nueva Guinea')
INTO Nationality (id, Name) VALUES (148, 'Paraguay')
INTO Nationality (id, Name) VALUES (149, 'Perú')
INTO Nationality (id, Name) VALUES (150, 'Polonia')
INTO Nationality (id, Name) VALUES (151, 'Portugal')
INTO Nationality (id, Name) VALUES (152, 'Reino Unido')
INTO Nationality (id, Name) VALUES (153, 'República Centroafricana')
INTO Nationality (id, Name) VALUES (154, 'República Checa')
INTO Nationality (id, Name) VALUES (155, 'República del Congo')
INTO Nationality (id, Name) VALUES (156, 'República Democrática del Congo')
INTO Nationality (id, Name) VALUES (157, 'República Dominicana')
INTO Nationality (id, Name) VALUES (158, 'República Sudafricana')
INTO Nationality (id, Name) VALUES (159, 'Ruanda')
INTO Nationality (id, Name) VALUES (160, 'Rumania')
INTO Nationality (id, Name) VALUES (161, 'Rusia')
INTO Nationality (id, Name) VALUES (162, 'Samoa')
INTO Nationality (id, Name) VALUES (163, 'San Cristóbal y Nieves')
INTO Nationality (id, Name) VALUES (164, 'San Marino')
INTO Nationality (id, Name) VALUES (165, 'San Vicente y las Granadinas')
INTO Nationality (id, Name) VALUES (166, 'Santa Lucía')
INTO Nationality (id, Name) VALUES (167, 'Santo Tomé y Príncipe')
INTO Nationality (id, Name) VALUES (168, 'Senegal')
INTO Nationality (id, Name) VALUES (169, 'Serbia')
INTO Nationality (id, Name) VALUES (170, 'Seychelles')
INTO Nationality (id, Name) VALUES (171, 'Sierra Leona')
INTO Nationality (id, Name) VALUES (172, 'Singapur')
INTO Nationality (id, Name) VALUES (173, 'Siria')
INTO Nationality (id, Name) VALUES (174, 'Somalia')
INTO Nationality (id, Name) VALUES (175, 'Sri Lanka')
INTO Nationality (id, Name) VALUES (176, 'Suazilandia')
INTO Nationality (id, Name) VALUES (177, 'Sudán')
INTO Nationality (id, Name) VALUES (178, 'Sudán del Sur')
INTO Nationality (id, Name) VALUES (179, 'Suecia')
INTO Nationality (id, Name) VALUES (180, 'Suiza')
INTO Nationality (id, Name) VALUES (181, 'Surinam')
INTO Nationality (id, Name) VALUES (182, 'Tailandia')
INTO Nationality (id, Name) VALUES (183, 'Taiwán')
INTO Nationality (id, Name) VALUES (184, 'Tanzania')
INTO Nationality (id, Name) VALUES (185, 'Tayikistán')
INTO Nationality (id, Name) VALUES (186, 'Timor Oriental')
INTO Nationality (id, Name) VALUES (187, 'Togo')
INTO Nationality (id, Name) VALUES (188, 'Tonga')
INTO Nationality (id, Name) VALUES (189, 'Trinidad y Tobago')
INTO Nationality (id, Name) VALUES (190, 'Túnez')
INTO Nationality (id, Name) VALUES (191, 'Turkmenistán')
INTO Nationality (id, Name) VALUES (192, 'Turquía')
INTO Nationality (id, Name) VALUES (193, 'Tuvalu')
INTO Nationality (id, Name) VALUES (194, 'Uganda')
INTO Nationality (id, Name) VALUES (195, 'Ucrania')
INTO Nationality (id, Name) VALUES (196, 'Uruguay')
INTO Nationality (id, Name) VALUES (197, 'Uzbekistán')
INTO Nationality (id, Name) VALUES (198, 'Vanuatu')
INTO Nationality (id, Name) VALUES (199, 'Venezuela')
INTO Nationality (id, Name) VALUES (200, 'Vietnam')
INTO Nationality (id, Name) VALUES (201, 'Yemen')
INTO Nationality (id, Name) VALUES (202, 'Yibuti')
INTO Nationality (id, Name) VALUES (203, 'Zambia')
INTO Nationality (id, Name) VALUES (204, 'Zimbabue')
SELECT 1 FROM dual;
COMMIT;

